name: Backend CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    env:
      TESTCONTAINERS_RYUK_DISABLED: "true"
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.7'
        
    - name: Build and Test
      run: gradle build --no-daemon

  deploy:
    needs: build_and_test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 95.165.175.66
        username: xxx
        port: 6969
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          mkdir -p ~/projects/kiotlinNew
          cd ~/projects/kiotlinNew
          
          if [ ! -d ".git" ]; then
            git init
            git remote add origin https://github.com/${{ github.repository }}.git
            git fetch --all
            git checkout -t origin/main -f
          else
            git fetch --all
            git reset --hard origin/main
          fi
          
          docker compose down
          docker compose up -d --build
